name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  scan:
    uses: ./.github/workflows/scan-job.yml
    secrets: inherit

  test:
    needs: scan
    uses: ./.github/workflows/test-job.yml
    secrets: inherit
    with:
      python-version: '3.12'

  results:
    needs: [test, scan]
    uses: ./.github/workflows/results-job.yml
    secrets: inherit
